version: '3'

services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    command: server --console-address ":9001" /data

  fake-news-classifier:
    image: fake-news-classifier:latest
    container_name: fake-news-classfier
    volumes:
      - ./tmp/data:/app/data
      - ./tmp/result:/app/result

volumes:
  minio_storage:
